# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: careamics_train_n2v
description: Train a Noise2Void (N2V) denoising model using CAREamics
keywords:
  - denoising
  - image restoration
  - image processing
  - microscopy
  - deep learning
  - careamics
  - noise2void
  - n2v
tools:
  - careamics:
      description: CAREamics is a library for content-aware image restoration in microscopy
      homepage: https://careamics.github.io
      documentation: https://careamics.github.io
      tool_dev_url: https://github.com/CAREamics/careamics
      licence: ["BSD-3-Clause"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information; passed through unchanged
  - train_data:
      type: file
      description: Training data as a single TIFF file or a directory containing TIFF files
      pattern: "*"
  - val_data:
      type: file
      description: Optional validation data as a single TIFF file or a directory containing TIFF files
      pattern: "*"
output:
  careamics_config:
    - - meta:
          type: map
          description: Groovy Map containing sample information; passed through unchanged
      - careamics.yaml:
          type: file
          description: CAREamics training configuration file
          pattern: "careamics.yaml"
  model:
    - - meta:
          type: map
          description: Groovy Map containing sample information; passed through unchanged
      - "checkpoints/*/*last.ckpt":
          type: file
          description: Trained model checkpoint
          pattern: "checkpoints/*/*last.ckpt"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@tatianawoller"
  - "@melisande-c"
maintainers:
  - "@melisande-c"
