# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: careamics_predict
description: Apply a trained CAREamics model to denoise images
keywords:
  - denoising
  - microscopy
  - deep learning
  - careamics
  - prediction
tools:
  - careamics:
      description: CAREamics is a library for content-aware image restoration in microscopy
      homepage: https://careamics.github.io
      documentation: https://careamics.github.io
      tool_dev_url: https://github.com/CAREamics/careamics
      licence: ["BSD-3-Clause"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id: 'test' ]
  - data:
      type: file
      description: Data to denoise as a .tif, .tiff, or .czi file, .zarr store, or directory containing image files
      pattern: "*.{tif,tiff,czi,zarr}"
  - data_inner_zarr_path:
      type: string
      description: Optional relative inner path to a zarr group within data. Leave null or empty to use data directly.
      pattern: "^(|[^/\\s][^\\s]*)$"
  - model:
      type: file
      description: Trained model checkpoint
      pattern: "*.ckpt"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id: 'test' ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - predictions:
      type: file
      description: Denoised predictions. File format is controlled by write_type.
      pattern: "predictions/*.{tiff,zarr}"
authors:
  - "@yourusername"
maintainers:
  - "@yourusername"
